pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    privileged: true
    environment:
      - SBT_TASK_LIMIT=4
      - AKKA_TEST_TIMEFACTOR=5
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - if $(git grep -qE "TODO|FIXME" *) ; then
          echo "Please remove TODO or FIXME. Create an issue at GitHub instead." ;
          exit 1 ;
        fi
      - echo "ensimeServerJars := Nil" > ensime.sbt ;
        echo "ensimeServerProjectJars := Nil" >> ensime.sbt ;
      - sbt ++$SCALA_VERSION ensimeConfig ";test:compile ;it:compile ;doc ;ensime/assembly";
        if $(! git diff --exit-code --quiet) ; then
          echo "Code formatting does not meet the project's standards:" ;
          git --no-pager diff ;
          exit 1 ;
        fi
      - if [ -n "$DRONE_PULL_REQUEST" ] ; then sbt ++$SCALA_VERSION "testOnly -- -l IgnoreOnDrone" ; fi
      - if [ -n "$DRONE_PULL_REQUEST" ] ; then sbt ++$SCALA_VERSION "it:testOnly -- -l IgnoreOnDrone" ; fi
      - if [ -z "$DRONE_PULL_REQUEST" ] ; then sbt ++$SCALA_VERSION publish ; fi
      - if [ -z "$DRONE_PULL_REQUEST" ] ; then
          echo "$SSH_KEY" > ~/.ssh/id_rsa ; chmod 600 ~/.ssh/id_rsa ;
          export ENSIME_ASSEMBLY_JAR=target/*/*-assembly.jar ;
          scp -o StrictHostKeyChecking=no $ENSIME_ASSEMBLY_JAR typelevel@ensime.typelevel.org:ensime.typelevel.org/ ;
        fi

matrix:
  SCALA_VERSION:
    - 2.11.8
    - 2.10.6
