pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    environment:
      - AKKA_TEST_TIMEFACTOR=10
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - if $(git grep -qE "TODO|FIXME" *) ; then
          echo "Please remove TODO or FIXME. Create an issue at GitHub instead." ;
          exit 1 ;
        fi
      - sbt ++$SCALA_VERSION ensimeConfig ";createHeaders ;test:createHeaders ;it:createHeaders ;test:compile ;it:compile ;doc ;ensime/assembly";
        if $(! git diff --exit-code --quiet) ; then
          echo "Code formatting does not meet the project's standards:" ;
          git --no-pager diff ;
          exit 1 ;
        fi
      - sbt ++$SCALA_VERSION "testOnly -- -l IgnoreOnDrone" ;
      - sbt ++$SCALA_VERSION "it:testOnly -- -l IgnoreOnDrone" ;
      - if [ -z "$DRONE_PULL_REQUEST" ] ; then
          sbt ++$SCALA_VERSION publish ;
          mkdir ~/.ssh ; echo $SSH_KEY > ~/.ssh/id_rsa ; chmod 644 ~/.ssh/id_rsa ;
          scp target/scala-2.1[01]/*-assembly.jar typelevel@ensime.typelevel.org:ensime.typelevel.org/ ;
          if [ "$SCALA_VERSION" = "2.11.8" ] ; then
            curl -H 'Content-Type:application/json' \
              --data '{"docker_tag":"v2.x-cache"}' \
              -X POST "https://registry.hub.docker.com/u/ensime/ensime/trigger/${DOCKER_TRIGGER_TOKEN}/"
          fi
        fi

matrix:
  SCALA_VERSION:
    - 2.11.8
    - 2.10.6
