branches:
  only:
  - master
  - scala-2.9
  - scala-2.10
language: scala
jdk:
- openjdk6
scala:
- 2.11.1
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test
- ./.check-diff.sh
- sbt ++$TRAVIS_SCALA_VERSION clean scoverage:test
after_success:
- sbt ++$TRAVIS_SCALA_VERSION clean publish
- sbt ++$TRAVIS_SCALA_VERSION scalastyleGenerateConfig scalastyle
# https://github.com/scoverage/sbt-coveralls/issues/18
#- sbt ++$TRAVIS_SCALA_VERSION coveralls
env:
  global:
    # travis encrypt -r ensime/ensime-server SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r ensime/ensime-server SONATYPE_PASSWORD=<PASSWORD>
    - secure: "IqDHZwYDAdif+BAJ0u57Ci7UEp4k0y8D+uDh51g6FqAIybD1HZ6TINojwj79675mjFaA9szXARkGAEuPfQ57tpC8Bevaj0zKX64TBE3HEdzuQL3i7dxi13DFEmCsUFeS7zqSMsqFcz5a6yASRujttDt2x0GCakOp82TvgI4NANM="
    - secure: "R90/HAOWcNEcs7CLx0ID/qLKBS9EC8Z52c9EPsmIx7dTWXGAOmbj7klUbWjkMsa/SkDYrfBTSPPsdW2QBY66pU8NeqL2YiguKNTVrOoFclEj/kfejQqJcII1PwwSBhVBXhp+bQ+ZHHe8MySDehK7hedL1fNzc8+RpLSUe2ROd90="
