branches:
  only:
    - master
    - scala-2.9
    - scala-2.10
language: scala
jdk:
  - openjdk6
  #- openjdk7
scala:
  - 2.11.6
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
addons:
  apt_packages:
  # https://github.com/travis-ci/apt-package-whitelist
  - openjdk-6-source
  #- openjdk-7-source
  # Travis doen't allow ppa's on its docker infrastructure but by
  # installing emacs23-gtk we get most of the dependencies we need to
  # run our own build of emacs-24.4.
  - emacs23-gtk
install:
  - curl -L $EMACS_URL | tar xjf - -C $HOME &&
    export EMACS=$HOME/emacs-${EMACS_VERSION}-bin/bin/emacs-${EMACS_VERSION} &&
    $EMACS --version
  - git clone --depth 1 https://github.com/ensime/ensime-emacs.git ../ensime-emacs
  - sbt ++$TRAVIS_SCALA_VERSION gen-ensime &&
    mkdir .ensime_cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile it:compile doc &&
    ./.check-diff.sh &&
    sbt ++$TRAVIS_SCALA_VERSION test it:test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal &&
    cd ../ensime-emacs &&
    test/run_emacs_tests.sh #2>&1 | tee stdout | grep "Starting test"
#after_failure:
#  - cat ../ensime-emacs/stdout
after_success:
  - cd ../ensime-server && sbt ++$TRAVIS_SCALA_VERSION $(if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then echo "publish"; fi)
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coveralls
env:
  global:
    - ENSIME_TEST_SERVER_VERSION=$TRAVIS_SCALA_VERSION
    - EMACS_VERSION=24.3 EMACS_URL=https://www.dropbox.com/s/iy3dqx5r378rpe6/emacs-24.3-bin.tar.bz2
    # travis encrypt -r ensime/ensime-server SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r ensime/ensime-server SONATYPE_PASSWORD=<PASSWORD>
    - secure: "IqDHZwYDAdif+BAJ0u57Ci7UEp4k0y8D+uDh51g6FqAIybD1HZ6TINojwj79675mjFaA9szXARkGAEuPfQ57tpC8Bevaj0zKX64TBE3HEdzuQL3i7dxi13DFEmCsUFeS7zqSMsqFcz5a6yASRujttDt2x0GCakOp82TvgI4NANM="
    - secure: "R90/HAOWcNEcs7CLx0ID/qLKBS9EC8Z52c9EPsmIx7dTWXGAOmbj7klUbWjkMsa/SkDYrfBTSPPsdW2QBY66pU8NeqL2YiguKNTVrOoFclEj/kfejQqJcII1PwwSBhVBXhp+bQ+ZHHe8MySDehK7hedL1fNzc8+RpLSUe2ROd90="
