language: scala
jdk:
- openjdk6
scala:
- 2.9.3
before_script:
- ./bintray.sh
after_success:
- sbt publish
env:
  global:
    # to generate this (when in the correct branch of the correct repo):
    # travis encrypt BINTRAY_TOKEN=<YOUR PRIVATE API KEY> --add
    secure: "Lqm0xJdy9ZVNAS4rKhzCKtzd0UXSVcg1APME+md4s8GH4rcWVxlz6RQvFbj1Rt/60lckI5JDgalKrvvOV8yIXyRAhxUt4KoJ1Kf6Pl+gHu7g0tRz3F0Ew50XTtxJfcuGe0T3OAg8nxzOGlR+bDCCuT1kkSE1E+LCFxY7LDqJcLc="
