install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt\bin\sbt.bat" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.0.4/sbt-1.0.4.zip',
          'C:\sbt-1.0.4.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-1.0.4.zip", "C:\")
      }
  - ps: |
      if (!(Test-Path -Path "C:\Program Files\Java\jdk1.8.0\src.zip")) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/fommil/openjdk8src/raw/master/src.zip',
          'C:\Program Files\Java\jdk1.8.0\src.zip'
        )
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET COURSIER_VERBOSITY=-1
  - cmd: SET AKKA_TEST_TIMEFACTOR=5
  - cmd: SET SBT_TASK_LIMIT=4
  - cmd: SET GC_LOGGING=true
  - cmd: SET SCALA_VERSION=2.12.4
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
build_script:
  - echo ensimeServerJars := Nil > ensime.sbt
  - echo ensimeServerProjectJars := Nil >> ensime.sbt
  - sbt ++%SCALA_VERSION%! ";prep ;cpl"
test_script:
  - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (sbt ++%SCALA_VERSION%! "testOnly -- -l tags.IgnoreOnAppVeyor")
  - SET SBT_TASK_LIMIT=2
  - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (sbt ++%SCALA_VERSION%! "it:testOnly -- -l tags.IgnoreOnAppVeyor")
cache:
  - C:\Program Files\Java\jdk1.8.0\src.zip
  - C:\sbt -> appveyor.yml
  - C:\Users\appveyor\.ivy2 -> appveyor.yml
  - C:\Users\appveyor\.coursier -> appveyor.yml
on_finish:
  - cmd: rmdir /S /Q testing target
  - ps: Get-ChildItem -Path $env:APPVEYOR_BUILD_FOLDER -Include .ensime,*.log,*.hprof -Recurse -Depth 2 | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
